# Generated by Django 6.0 on 2025-12-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_hospital', '0002_hospital_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='total_doctors',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='services',
        ),
        migrations.AddField(
            model_name='hospital',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='hospitals', to='find_hospital.department'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='hospitals', to='find_hospital.service'),
        ),
    ]
