# Generated by Django 6.0 on 2025-12-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_hospital', '0003_department_service_remove_hospital_total_doctors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='total_website_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
