# Generated by Django 6.0 on 2025-12-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_hospital', '0004_hospital_total_views_hospital_total_website_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='appointment_link',
            field=models.URLField(blank=True, help_text="Direct link to the hospital's booking page", null=True),
        ),
    ]
