# Generated by Django 5.0.14 on 2026-02-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_hospital', '0005_hospital_appointment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalreview',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
