# Generated by Django 6.0 on 2025-12-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='allergies',
            field=models.TextField(blank=True, help_text='Comma separated allergies'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='chronic_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='medications',
            field=models.TextField(blank=True, help_text='Current medications'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='patients/profile_pics/'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in kg', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
