# Generated by Django 5.0.14 on 2026-03-27 13:20

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_patientprofile_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='date_of_birth',
            field=encrypted_model_fields.fields.EncryptedDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='mobile_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
    ]
