# Generated by Django 5.0.14 on 2026-03-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_patientprofile_date_of_birth_and_more'),
        ('find_doctor', '0007_doctorprofile_auto_accept_appointments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='favorite_doctors',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_patients', to='find_doctor.doctorprofile'),
        ),
    ]
