# Generated by Django 5.0.14 on 2026-03-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_patientprofile_favorite_doctors'),
        ('find_hospital', '0006_hospitalreview_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='favorite_hospitals',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_patients', to='find_hospital.hospital'),
        ),
    ]
