"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
load_dotenv()
from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
FIELD_ENCRYPTION_KEY = os.getenv('FIELD_ENCRYPTION_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'

# ALLOWED_HOSTS = ['localhost', '127.0.0.1']
ALLOWED_HOSTS = [
           'localhost',
           '127.0.0.1',
           '.onrender.com',        # Allows all Render subdomains
       ]


# Application definition

INSTALLED_APPS = [
    'daphne',  # Must be at the top for ASGI support
    'accounts',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'pages',
    'find_doctor',
    'find_hospital',    
    'appointments',
    'doctorAdmin',
    'superAdmin',
    'hospitalAdmin',
    
    #for Allauth apps 
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',   # For Google
    'allauth.socialaccount.providers.facebook', # For Facebook
    
    'django.contrib.humanize',
    
    # WebSocket Support
    'channels',
    'encrypted_model_fields',
]

SITE_ID = 1  


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # EXPLANATION: WhiteNoiseMiddleware allows your Django app to serve its own static files (CSS, JS, Images) efficiently.
    # PROD REASON: Without this, when you deploy to Render/Heroku, your site will look "broken" (no styles) because 
    # web servers (like Gunicorn) generally don't serve static files by default. WhiteNoise fixes this.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'myproject.middleware.ExceptionLoggingMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

# ASGI Application for WebSocket Support
ASGI_APPLICATION = 'myproject.asgi.application'

# Channel Layers Configuration (In-Memory for Development)
# For production, use Redis: 'channels_redis.core.RedisChannelLayer'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}

# For production with Redis (uncomment when deploying):
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [('127.0.0.1', 6379)],
#         },
#     },
# }





# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases




# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'docplus_db',  
#         'USER': 'macm2',    
#         'PASSWORD': '',       
#         'HOST': '127.0.0.1',
#         'PORT': '5432',
#     }
# }


import dj_database_url

# Use DATABASE_URL from environment if available (Render),
# otherwise fall back to local PostgreSQL
if os.getenv('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.getenv('DATABASE_URL'),
            conn_max_age=600
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'docplus_db',
            'USER': 'macm2',
            'PASSWORD': '',
            'HOST': '127.0.0.1',
            'PORT': '5432',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

#*uncomment this after testing for strong password in production
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",     
]

# EXPLANATION: This tells Django where to collect all static files when you run 'python manage.py collectstatic'.
# PROD REASON: In production, all your scattered static files need to be gathered into one folder for WhiteNoise to serve them.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# EXPLANATION: This configures Django to use WhiteNoise for static file storage.
# PROD REASON: 'CompressedManifestStaticFilesStorage' does two things:
# 1. Compresses files (Gzip/Brotli) to make your site load faster.
# 2. Adds a unique hash to filenames (e.g., style.123abc4.css) for long-term browser caching.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

LOGIN_REDIRECT_URL = '/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'

import os

# Base URL to access files in browser
MEDIA_URL = '/media/'

# Where files are physically stored on your machine
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# 30 minutes * 60 seconds = 1800
SESSION_COOKIE_AGE = 86400 #one day 
SESSION_SAVE_EVERY_REQUEST = True # Resets the timer if they click a link





# Redirect to login page after logout
LOGOUT_REDIRECT_URL = 'login'


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend', # Needed to login by username in Django admin
    'allauth.account.auth_backends.AuthenticationBackend', # Needed for social login
]

# ACCOUNT_USER_MODEL_USERNAME_FIELD = None # You use email, not username


SOCIALACCOUNT_LOGIN_ON_GET = True # Skips the "Are you sure?" intermediate screen
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']  # replaces deprecated EMAIL_REQUIRED / USERNAME_REQUIRED
ACCOUNT_LOGIN_METHODS = {'email'}       # login via email only (no username)
ACCOUNT_EMAIL_VERIFICATION = 'none'    # Social login users (Google/FB) are already verified

# 5. Provider Settings (Put Keys HERE to avoid using Admin Panel)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID'),
            'secret': os.getenv('GOOGLE_SECRET'),
            'key': ''
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'}
    },
    'facebook': {
        'APP': {
            'client_id': os.getenv('FACEBOOK_CLIENT_ID'),
            'secret': os.getenv('FACEBOOK_SECRET'),
            'key': ''
        },
        'METHOD': 'oauth2',
        'SDK_URL': '//connect.facebook.net/{locale}/sdk.js',
        'SCOPE': ['email', 'public_profile'],
        'FIELDS': ['id', 'email', 'name', 'first_name', 'last_name'],
        'EXCHANGE_TOKEN': True,
    }
}


# ── Email / SMTP ────────────────────────────────────────────────────────────
EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST          = 'smtp.gmail.com'
EMAIL_PORT          = 587
EMAIL_USE_TLS       = True
EMAIL_HOST_USER     = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL  = os.getenv('EMAIL_HOST_USER')  # "From:" address for all outgoing mail

# Khalti Payment Gateway (Sandbox)
KHALTI_SECRET_KEY = os.getenv('KHALTI_SECRET_KEY')
KHALTI_PUBLIC_KEY = os.getenv('KHALTI_PUBLIC_KEY')
KHALTI_BASE_URL = 'https://dev.khalti.com/api/v2'

# eSewa Payment Gateway (Sandbox/UAT)
ESEWA_SECRET_KEY    = os.getenv('ESEWA_SECRET_KEY', '8gBm/:&EnhH.1/q')
ESEWA_PRODUCT_CODE  = os.getenv('ESEWA_PRODUCT_CODE', 'EPAYTEST')
ESEWA_PAYMENT_URL   = os.getenv('ESEWA_PAYMENT_URL', 'https://rc-epay.esewa.com.np/api/epay/main/v2/form')

# ── Production Security Settings ────────────────────────────
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    CSRF_TRUSTED_ORIGINS = [
        'https://*.onrender.com',]
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True