# Generated by Django 6.0 on 2025-12-08 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('find_doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('medical_reports', models.FileField(blank=True, null=True, upload_to='medical_reports/')),
                ('payment_method', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=900.0, max_digits=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='find_doctor.doctorprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
