# Generated by Django 6.0 on 2025-12-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(default='09:30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(default='09:00'),
            preserve_default=False,
        ),
    ]
