# Generated by Django 6.0 on 2026-01-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_call_access_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_approved_call',
            field=models.BooleanField(default=False),
        ),
    ]
