# Generated by Django 5.0.14 on 2026-03-18 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_khalti_pidx_appointment_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='refund_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='refund_status',
            field=models.CharField(choices=[('none', 'No Refund'), ('requested', 'Refund Requested'), ('completed', 'Refund Completed'), ('failed', 'Refund Failed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='appointments.appointment'),
        ),
    ]
