# Generated by Django 5.0.14 on 2026-03-27 13:20

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='symptoms',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
    ]
