# Generated by Django 6.0 on 2025-12-08 08:39

import django.db.models.deletion
import find_doctor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('find_hospital', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('city', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=find_doctor.models.user_directory_path)),
                ('specialization', models.CharField(max_length=100)),
                ('sub_specialty', models.CharField(blank=True, max_length=100, null=True)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('registration_council', models.CharField(max_length=100)),
                ('years_of_experience', models.PositiveSmallIntegerField()),
                ('hospital_name_manual', models.CharField(blank=True, help_text='If your hospital is not listed above, type the name here.', max_length=150, null=True)),
                ('current_position', models.CharField(blank=True, max_length=100, null=True)),
                ('languages_spoken', models.CharField(blank=True, max_length=200, null=True)),
                ('medical_degree', models.CharField(max_length=100)),
                ('medical_school', models.CharField(max_length=150)),
                ('graduation_year', models.PositiveSmallIntegerField()),
                ('consultation_fee', models.PositiveIntegerField(help_text='In NPR')),
                ('bio', models.TextField(blank=True, null=True)),
                ('cv', models.FileField(upload_to=find_doctor.models.user_directory_path)),
                ('medical_license_doc', models.FileField(upload_to=find_doctor.models.user_directory_path)),
                ('degree_certificate', models.FileField(upload_to=find_doctor.models.user_directory_path)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital_affiliation', models.ForeignKey(blank=True, help_text='Select if your hospital is registered with us.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliated_doctors', to='find_hospital.hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='find_doctor.doctorprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'doctor')},
            },
        ),
    ]
