# Generated by Django 6.0 on 2025-12-10 08:26

import django.contrib.postgres.fields
import find_doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='available_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, help_text="Comma-separated days, e.g., 'Mon, Wed, Fri'"),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='available_time_end',
            field=models.TimeField(help_text='End time (e.g. 17:00:00)', null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='available_time_start',
            field=models.TimeField(default='9:00', help_text='Start time (e.g. 09:00:00)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='current_position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='hospital_name_manual',
            field=models.CharField(help_text='If your hospital is not listed above, type the name here.', max_length=150),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='languages_spoken',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='profile_photo',
            field=models.ImageField(upload_to=find_doctor.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='sub_specialty',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
