# Generated by Django 6.0 on 2025-12-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_doctor', '0003_doctorschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='sub_specialty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
