# Generated by Django 6.0 on 2026-01-10 03:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_doctor', '0004_alter_doctorprofile_sub_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Medical specialty name (e.g., Cardiology, Neurology)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this specialty')),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, help_text="Symptoms and diseases (lowercase): e.g., ['chest pain', 'heart attack', 'hypertension']")),
                ('sub_specialties', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Sub-specializations within this field')),
                ('priority', models.PositiveSmallIntegerField(default=5, help_text='Higher priority specialties rank first for ambiguous symptoms (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medical Specialty',
                'verbose_name_plural': 'Medical Specialties',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
