# Generated by Django 5.0.14 on 2026-02-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_doctor', '0006_doctorreview_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='auto_accept_appointments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='enable_video_consultations',
            field=models.BooleanField(default=True),
        ),
    ]
